// <auto-generated />
using System;
using AnallyzerAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AnallyzerAPI.Migrations
{
    [DbContext(typeof(AnallyzerDbContext))]
    partial class AnallyzerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnallyzerAPI.Models.Campain", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("dt_companies");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("dt_descriptions");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_forecastdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("dt_names");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_registrationdate");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_startdate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("dt_status");

                    b.HasKey("ID");

                    b.ToTable("TB_CAMPAINS");
                });
#pragma warning restore 612, 618
        }
    }
}
